name: Auto Cherry-Pick to Release Branch

on:
  pull_request:
    types: [closed]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    name: Backport to release branch
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' &&
        github.event.pull_request.merged == true) ||
      (github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        startsWith(github.event.comment.body, '/backport'))
    steps:
      - name: Backport Action
        uses: korthout/backport-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_description: |
            Backport of #${pull_number}

            ${pull_description}
